Dev
Make-senior-cry/KOTIKI-frontend pull request #31
Opened 2023-05-13 16:38 UTC by temerk1n

Some fixes and few changes

2023-05-13 17:11 UTC, vladislavkn commented on src/store/postsStore.js
> +  FOLLOWING: 'FOLLOWING',
Тат просто так больше нравится?

2023-05-13 17:14 UTC, vladislavkn requested changes

2023-05-13 17:14 UTC, vladislavkn commented on src/ui/DefaultLayout.jsx
> +        {!showError
По возможности лучше не использовать условия с отрицанием - их сложнее читать. Тут можно написать, например, const noError = errorMessage.length === 0, и потом noError ? children : <...>, или просто поменять метами children и Alert в тернарном операторе, тогда можно убрать ! перед showError

2023-05-13 17:26 UTC, temerk1n commented on src/store/postsStore.js
> +  FOLLOWING: 'FOLLOWING',
Синхронизация с бэком

2023-05-14 08:17 UTC, temerk1n commented on src/ui/DefaultLayout.jsx
> +        {!showError
Пофиксил в ветке feat/profile

2023-05-14 08:17 UTC, temerk1n commented
Можно закрывать ПР

2023-05-15 07:32 UTC, closed without merging