Feat/profile
Make-senior-cry/KOTIKI-frontend pull request #33
Opened 2023-05-14 11:40 UTC by temerk1n

2023-05-14 11:41 UTC, temerk1n commented
Надо еще упросить profilePage

2023-05-14 11:54 UTC, vladislavkn requested changes

2023-05-14 11:54 UTC, vladislavkn commented on src/api/getPosts.js
> +    const postExample = new PostRecord({
Добавь пожалуйста в конфиг настройку, чтобы можно было  переключать реальный запрос постов и просто возврат моков. Это нужно, чтобы управлять поведением приложения через переменные окружения, без необходимости изменения кода

2023-05-14 11:54 UTC, vladislavkn commented on src/pages/ProfilePage.jsx
> +  useEffect(() => {
Подскажи, что тут за логика?

2023-05-14 11:54 UTC, vladislavkn commented on src/pages/ProfilePage.jsx
> +    console.log('FOLLOW');
Тут нужен console log?

2023-05-14 11:54 UTC, vladislavkn commented on src/ui/PostPaginatedList/PostPaginatedListPagination.jsx
> -            Слелующая страница
?_?)

2023-05-14 11:58 UTC, temerk1n commented on src/ui/PostPaginatedList/PostPaginatedListPagination.jsx
> -            Слелующая страница
Опечатка?

2023-05-14 12:08 UTC, temerk1n commented on src/pages/ProfilePage.jsx
> +  useEffect(() => {
Проверяем, профиль какого пользователя отрисовывать (авторизованного пользователя или какого-то другого)

2023-05-14 12:08 UTC, temerk1n commented on src/pages/ProfilePage.jsx
> +    console.log('FOLLOW');
Запрос на фоллоу еще не написан

2023-05-14 12:32 UTC, temerk1n commented on src/api/getPosts.js
> +    const postExample = new PostRecord({
Добавил

2023-05-15 07:17 UTC, vladislavkn requested changes

2023-05-15 07:17 UTC, vladislavkn commented on src/api/follow.js
> +    console.log(response);
Если console.log больше не нужен для разработки, то давай уберем?

2023-05-15 07:17 UTC, vladislavkn commented on src/api/getPosts.js
> +    if (config.MODE === 'development') {
Тут можно if вынести над уровнем httpClient.post, потому что иначе даже в дев режиме будет выполняться запрос к серверу и, если произойдет ошибка, то мы не получим даже этих моковых постов

2023-05-15 07:17 UTC, vladislavkn commented on src/pages/ProfilePage.jsx
> +    API.isFollower(userId)
Это значит "является ли текущий пользователь фолловером пользователя с id=userId?". Если да, то давай переименуем api функцию в isFollowedByCurrentUser(userId)

2023-05-15 07:17 UTC, vladislavkn commented on src/pages/ProfilePage.jsx
> +  useEffect(() => {
Не очень понятно просто со строкой user.id !== userId. Можешь это условие в отдельную переменную вынести пожалуйста, чтобы было понятно, что оно означает?

2023-05-15 07:17 UTC, vladislavkn commented on src/pages/ProfilePage.jsx
> +        isFollow();
Может лучше назовем updateIsFollowing? Иначе функция будто должна true/false возвращать, а не обновлять состояние

2023-05-15 19:42 UTC, vladislavkn requested changes

2023-05-15 19:42 UTC, vladislavkn commented on src/api/getUser.js
> +    return new User(response.data);
Тут user нужно передавать. И давай назовем userData

2023-05-15 19:42 UTC, vladislavkn commented on src/pages/ProfilePage.jsx
> +  const isCorrectUserRendered = parseInt(user.id, 10) !== parseInt(userId, 10);
Тут мб uncorrectUserRendered?

2023-05-15 19:42 UTC, vladislavkn commented on src/pages/ProfilePage.jsx
> +  });
useEffect без зависимостей будет каждый рендер вызываться. Давай сделаем зависимым от uncorrectUserRendered

2023-05-15 21:00 UTC, vladislavkn approved these changes

2023-05-15 21:00 UTC, merged